<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnHapus</name>
   <tag></tag>
   <elementGuidId>ecfab569-1fdf-4513-85a0-2cc9e7e4b732</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody/tr[1]/td[6]/button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.ant-btn-danger.ant-tooltip-open</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb380c49-74e3-422d-b675-21863c07a6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nztooltiptitle</name>
      <type>Main</type>
      <value>Hapus data cabang</value>
      <webElementGuid>a5c40e33-a526-498d-ab47-585dbe4dd581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nztooltipplacement</name>
      <type>Main</type>
      <value>topRight</value>
      <webElementGuid>afc6b5c9-55f4-4678-af3c-1c346510939f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nztype</name>
      <type>Main</type>
      <value>danger</value>
      <webElementGuid>08095bc8-c273-4318-b82f-f53bd2f129d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nzpopconfirmtitle</name>
      <type>Main</type>
      <value>Anda yakin akan menghapus data cabang ini?</value>
      <webElementGuid>30b8e138-a50d-45b7-adca-44aea397d749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nzpopconfirmplacement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>f308b79e-6c10-4896-91db-10af4574cdc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-danger ant-tooltip-open</value>
      <webElementGuid>b8cb1510-855c-4316-8e0f-ba8d543ac0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Hapus </value>
      <webElementGuid>f79fe0d9-1702-40e8-86c8-1f45d92d2797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-layout[@class=&quot;ant-layout&quot;]/nz-content[@class=&quot;ant-layout-content&quot;]/app-master-plant-index[@class=&quot;ng-star-inserted&quot;]/nz-table[@class=&quot;ant-table-wrapper&quot;]/nz-spin[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container ng-star-inserted&quot;]/div[@class=&quot;ant-table&quot;]/nz-table-inner-default[@class=&quot;ant-table-container ng-star-inserted&quot;]/div[@class=&quot;ant-table-content&quot;]/table[1]/tbody[@class=&quot;ant-table-tbody ng-star-inserted&quot;]/tr[@class=&quot;ant-table-row ng-star-inserted&quot;]/td[@class=&quot;ant-table-cell&quot;]/button[@class=&quot;ant-btn ant-btn-danger ant-tooltip-open&quot;]</value>
      <webElementGuid>dfeb9a26-3a1c-432e-8329-d2f46d9b11b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bagussetiadi@yahoo.com'])[1]/following::button[1]</value>
      <webElementGuid>c40f0276-b6f1-4208-8745-55c5304c70c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bagussetiadi'])[3]/following::button[1]</value>
      <webElementGuid>ae2dff1f-1bc2-43ed-855a-243094c621a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::button[1]</value>
      <webElementGuid>fe5508bb-b5b5-4c41-bd0a-197fba96b377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/button</value>
      <webElementGuid>7c0cec67-245b-4475-88ed-4a3fc54431ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Hapus ' or . = ' Hapus ')]</value>
      <webElementGuid>050b2690-6ac6-4bed-810d-b7b48b8ae544</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
