<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnManajemenRole</name>
   <tag></tag>
   <elementGuidId>ac0c3cba-5749-41ec-9862-234f4bee02f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Selisih Penerimaan Barang'])[2]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8b9cdf32-1000-46f9-90bb-6cb860e74329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/manajemen-role</value>
      <webElementGuid>d1e4e425-6640-43ad-82e8-a24150649728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manajemen Role </value>
      <webElementGuid>9f9579d9-ed33-467c-91f0-2e005aa932b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-sider[@class=&quot;ant-layout-sider ant-layout-sider-light&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/perfect-scrollbar[@class=&quot;aside-menu my-4 scroll ps ps--active-y&quot;]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-light ant-menu-inline&quot;]/app-sider[1]/li[@class=&quot;ant-menu-item ng-star-inserted&quot;]/a[1]</value>
      <webElementGuid>6e4a2ca6-7b84-4e44-8d73-86076622c42d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selisih Penerimaan Barang'])[2]/following::a[1]</value>
      <webElementGuid>9de72100-bbd3-43b6-9eef-7a664e3ff0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checklist Perawatan Gudang'])[2]/following::a[2]</value>
      <webElementGuid>ea2a9957-596d-48c8-815b-488b9422a92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Aplikasi'])[1]/preceding::a[1]</value>
      <webElementGuid>511cba9a-588d-4f47-9a0e-0039c5427453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/manajemen-role')]</value>
      <webElementGuid>2ead29f6-32a1-4687-9e8e-75f793aca033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>33c11f96-a985-4cb7-a108-36b4ac6b1906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/manajemen-role' and (text() = 'Manajemen Role ' or . = 'Manajemen Role ')]</value>
      <webElementGuid>3ce7d571-3a91-4215-ab52-243957e7814b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
