<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkDashboard</name>
   <tag></tag>
   <elementGuidId>15c0aebc-4768-45be-a893-d5077a4ddb94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[55]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.ant-checkbox-wrapper.ng-valid.ng-dirty.ng-touched.cdk-focused.cdk-keyboard-focused > span.ant-checkbox > input.ant-checkbox-input.ng-valid.ng-touched.ng-dirty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>098b4f57-1c3e-4d49-950e-214bc94f8f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3319206f-72a2-42ad-b217-f96e16f2ad64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-checkbox-input ng-valid ng-touched ng-dirty</value>
      <webElementGuid>e21217d3-5d21-47a5-8614-231ef3481f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-base[@class=&quot;ng-star-inserted&quot;]/nz-layout[@class=&quot;app-layout ant-layout-has-sider ant-layout&quot;]/nz-layout[@class=&quot;ant-layout&quot;]/nz-content[@class=&quot;ant-layout-content&quot;]/app-role-management-form[@class=&quot;ng-star-inserted&quot;]/nz-spin[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container ng-star-inserted&quot;]/nz-card[@class=&quot;kt-mt-10 kt-mb-20 ant-card ant-card-bordered&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-row ng-star-inserted&quot;]/div[@class=&quot;kt-mb-30 pr-10 ant-col ant-col-24 ant-col-md-12 ant-col-lg-12 ng-star-inserted&quot;]/div[@class=&quot;kt-mb-20 ant-row&quot;]/div[@class=&quot;ant-col ant-col-24&quot;]/label[@class=&quot;ant-checkbox-wrapper ng-valid ng-dirty ng-touched cdk-focused cdk-keyboard-focused&quot;]/span[@class=&quot;ant-checkbox&quot;]/input[@class=&quot;ant-checkbox-input ng-valid ng-touched ng-dirty&quot;]</value>
      <webElementGuid>2f1b5a24-507b-49e6-ad7c-cd837f3a4840</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[55]</value>
      <webElementGuid>9c95e371-a813-48a7-9a16-982be03d6953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/label/span/input</value>
      <webElementGuid>f06e4e21-fe68-41b1-a60f-c4752a694ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>18cb6395-61d5-4dfd-90e7-26ff7728cd36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
