<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldUsername</name>
   <tag></tag>
   <elementGuidId>fe13f60d-dd4f-4a9e-a171-2ca30962a85f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='app_login_form_username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#app_login_form_username</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b030866-5137-431a-8185-6790d37e7828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>app_login_form_username</value>
      <webElementGuid>a578c91e-c44f-4113-9394-cbaeb8f91b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97bf40c1-1d50-4e95-87ad-4d47ad152334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>86caf332-64b0-406c-8d79-bd02c558413d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>523c4dac-717f-496e-b849-fd98d2d94dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>362b8900-e689-4303-98bf-0e2b9a16cd0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app_login_form_username&quot;)</value>
      <webElementGuid>e64f8513-1da7-4a50-9a60-fb5fb795a5ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='app_login_form_username']</value>
      <webElementGuid>47410f5e-ac85-436b-98d6-f9b878c23657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nz-form-control[@id='form_control_login no-padding']/div/div/nz-input-group/input</value>
      <webElementGuid>29d11cc7-5929-4dff-b308-94842b444424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>54002e79-ae7f-4bea-bb5a-45b633d7f41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'app_login_form_username' and @type = 'text' and @placeholder = 'Username']</value>
      <webElementGuid>3dc1441e-ec3e-4a93-8136-3e2d7ac77cb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
